-- H2 2.4.240;
SET DB_CLOSE_DELAY -1;        
;             
CREATE USER IF NOT EXISTS "SA" SALT '701dfea5f4b9260b' HASH 'bec2b75f9e2dee0e40dc15ebec0ee964346a619bef2856c76c84fcd6e8ed3d84' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."EXAMS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) DEFAULT ON NULL NOT NULL,
    "CATEGORY" CHARACTER VARYING(255) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(1000),
    "NAME" CHARACTER VARYING(255) NOT NULL
);   
ALTER TABLE "PUBLIC"."EXAMS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");        
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.EXAMS;   
INSERT INTO "PUBLIC"."EXAMS" VALUES
(1, 'Java', 'Java language fundamentals, OOP, and collections for interview prep.', 'Core Java'),
(2, 'Spring Boot', 'Spring Boot, Spring MVC, Spring Data JPA, and Spring Security essentials.', 'Spring Boot'),
(3, 'AWS', 'Core AWS services, pricing, and architecture for certification prep.', 'AWS Cloud Practitioner'),
(4, 'Azure', 'Core Azure services, governance, and pricing for AZ-900 style prep.', 'Azure Fundamentals');            
CREATE MEMORY TABLE "PUBLIC"."PAYMENT_ORDER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "AMOUNT" BIGINT NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "CURRENCY" CHARACTER VARYING(10) NOT NULL,
    "RAZORPAY_ORDER_ID" CHARACTER VARYING(100) NOT NULL,
    "RECEIPT" CHARACTER VARYING(100) NOT NULL,
    "STATUS" ENUM('CANCELLED', 'CREATED', 'FAILED', 'PAID') NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "PLAN_ID" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL
);    
ALTER TABLE "PUBLIC"."PAYMENT_ORDER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PAYMENT_ORDER;           
CREATE MEMORY TABLE "PUBLIC"."PAYMENT_TRANSACTION"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "PAYMENT_METHOD" CHARACTER VARYING(50),
    "RAZORPAY_PAYMENT_ID" CHARACTER VARYING(100) NOT NULL,
    "RAZORPAY_SIGNATURE" CHARACTER VARYING(255) NOT NULL,
    "STATUS" ENUM('FAILED', 'SUCCESS') NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "ORDER_ID" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL
);       
ALTER TABLE "PUBLIC"."PAYMENT_TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_39" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PAYMENT_TRANSACTION;     
CREATE MEMORY TABLE "PUBLIC"."PLAN_QUESTION"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 101) DEFAULT ON NULL NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "PLAN_ID" BIGINT NOT NULL,
    "QUESTION_ID" BIGINT NOT NULL
);       
ALTER TABLE "PUBLIC"."PLAN_QUESTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");
-- 100 +/- SELECT COUNT(*) FROM PUBLIC.PLAN_QUESTION;         
INSERT INTO "PUBLIC"."PLAN_QUESTION" VALUES
(1, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 1),
(2, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 1),
(3, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 1),
(4, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 1),
(5, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 2),
(6, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 2),
(7, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 2),
(8, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 3),
(9, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 3),
(10, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 4),
(11, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 5),
(12, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 5),
(13, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 5),
(14, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 5),
(15, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 6),
(16, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 6),
(17, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 6),
(18, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 7),
(19, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 7),
(20, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 8),
(21, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 9),
(22, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 9),
(23, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 9),
(24, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 9),
(25, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 10),
(26, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 10),
(27, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 10),
(28, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 11),
(29, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 11),
(30, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 12),
(31, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 13),
(32, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 13),
(33, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 13),
(34, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 13),
(35, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 14),
(36, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 14),
(37, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 14),
(38, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 15),
(39, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 15),
(40, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 16),
(41, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 17),
(42, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 17),
(43, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 17),
(44, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 17),
(45, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 18),
(46, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 18),
(47, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 18),
(48, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 19),
(49, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 19),
(50, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 20),
(51, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 21),
(52, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 21),
(53, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 21),
(54, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 21),
(55, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 22),
(56, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 22),
(57, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 22),
(58, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 23);    
INSERT INTO "PUBLIC"."PLAN_QUESTION" VALUES
(59, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 23),
(60, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 24),
(61, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 25),
(62, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 25),
(63, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 25),
(64, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 25),
(65, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 26),
(66, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 26),
(67, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 26),
(68, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 27),
(69, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 27),
(70, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 28),
(71, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 29),
(72, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 29),
(73, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 29),
(74, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 29),
(75, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 30),
(76, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 30),
(77, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 30),
(78, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 31),
(79, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 31),
(80, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 32),
(81, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 33),
(82, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 33),
(83, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 33),
(84, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 33),
(85, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 34),
(86, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 34),
(87, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 34),
(88, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 35),
(89, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 35),
(90, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 36),
(91, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 1, 37),
(92, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 37),
(93, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 37),
(94, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 37),
(95, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 2, 38),
(96, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 38),
(97, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 38),
(98, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 3, 39),
(99, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 39),
(100, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.408572+00', 4, 40);  
CREATE INDEX "PUBLIC"."IDX_PLAN_QUESTION_PLAN_ID" ON "PUBLIC"."PLAN_QUESTION"("PLAN_ID" NULLS FIRST);         
CREATE INDEX "PUBLIC"."IDX_PLAN_QUESTION_QUESTION_ID" ON "PUBLIC"."PLAN_QUESTION"("QUESTION_ID" NULLS FIRST); 
CREATE MEMORY TABLE "PUBLIC"."QUESTIONS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 41) DEFAULT ON NULL NOT NULL,
    "ANSWER" CHARACTER VARYING(10) NOT NULL,
    "DIFFICULTY" CHARACTER VARYING(20),
    "EXPLANATION" CHARACTER VARYING(2000),
    "OPTIONA" CHARACTER VARYING(1000) NOT NULL,
    "OPTIONB" CHARACTER VARYING(1000) NOT NULL,
    "OPTIONC" CHARACTER VARYING(1000) NOT NULL,
    "OPTIOND" CHARACTER VARYING(1000) NOT NULL,
    "QUESTION" CHARACTER VARYING(2000) NOT NULL,
    "EXAM_ID" BIGINT NOT NULL
);               
ALTER TABLE "PUBLIC"."QUESTIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3B" PRIMARY KEY("ID");   
-- 40 +/- SELECT COUNT(*) FROM PUBLIC.QUESTIONS;              
INSERT INTO "PUBLIC"."QUESTIONS" VALUES
(1, 'B', 'MEDIUM', '''final'' on a class prevents any other class from extending it.', 'static', 'final', 'const', 'sealed', 'Which keyword is used to prevent a class from being subclassed in Java?', 1),
(2, 'B', 'MEDIUM', 'Uninitialized boolean fields default to false.', 'true', 'false', 'null', '0', 'What is the default value of a boolean instance variable in Java?', 1),
(3, 'C', 'MEDIUM', 'Set implementations like HashSet enforce uniqueness of elements.', 'ArrayList', 'LinkedList', 'HashSet', 'PriorityQueue', 'Which collection type does NOT allow duplicate elements?', 1),
(4, 'C', 'MEDIUM', 'IOException extends Exception directly and must be declared or caught; the others are unchecked RuntimeExceptions.', 'NullPointerException', 'ArithmeticException', 'IOException', 'ArrayIndexOutOfBoundsException', 'Which of these is a checked exception in Java?', 1),
(5, 'B', 'MEDIUM', U&'''volatile'' ensures visibility \2014 reads always see the latest write \2014 but does not make compound operations atomic.', 'Thread-safety for compound operations', 'Visibility of writes across threads', 'Atomicity of increment operations', 'Immutability', 'What does the ''volatile'' keyword guarantee for a field?', 1),
(6, 'C', 'MEDIUM', 'HashMap relies on a consistent equals()/hashCode() implementation to locate buckets and detect key equality.', 'Comparable', 'Serializable', 'equals()/hashCode() contract', 'Cloneable', 'Which interface must a class implement to be used as a key in a HashMap reliably?', 1),
(7, 'A', 'MEDIUM', 'ArrayList is backed by an array, so indexed access is constant time.', 'O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 'What is the time complexity of retrieving an element from an ArrayList by index?', 1),
(8, 'C', 'MEDIUM', 'Lambdas can capture local variables only if they are final or effectively final.', 'Any local variable', 'Only static variables', 'Effectively final local variables', 'Only instance fields', 'Which Java feature allows a lambda expression to access an enclosing local variable?', 1),
(9, 'B', 'MEDIUM', 'reduce() folds the stream elements into one result via a combining function.', 'Filters elements matching a predicate', 'Combines elements into a single result using an accumulator', 'Sorts the stream', 'Skips duplicate elements', 'What does the Stream API''s ''reduce'' operation do?', 1),
(10, 'B', 'MEDIUM', 'The JVM''s garbage collector automatically reclaims memory for objects no longer reachable from GC roots.', 'Manual memory deallocation via free()', 'Automatic reclamation of unreachable objects', 'Only runs when JVM exits', 'Requires explicit destructor calls', 'Which of these correctly describes Java''s garbage collection?', 1),
(11, 'B', 'MEDIUM', '@SpringBootApplication combines @Configuration, @EnableAutoConfiguration, and @ComponentScan.', '@Component', '@SpringBootApplication', '@Configuration', '@Service', 'Which annotation marks a class as a Spring Boot application entry point?', 2),
(12, 'B', 'MEDIUM', 'Auto-configuration inspects the classpath and existing beans to wire up sensible defaults automatically.', 'To require XML config for every bean', 'To automatically configure beans based on classpath contents and properties', 'To disable all default beans', 'To replace dependency injection', 'What is the purpose of Spring Boot''s auto-configuration?', 2),
(13, 'B', 'MEDIUM', '@Autowired is Spring''s primary annotation for dependency injection by type.', '@Inject only', '@Autowired', '@Resource only', '@Bean', 'Which annotation is used to inject a bean by type in Spring?', 2),
(14, 'B', 'MEDIUM', '''update'' incrementally alters the schema to match entity mappings, preserving existing data.', 'Drops and recreates the schema on every start', 'Updates the schema to match entities without dropping existing data', 'Disables schema generation', 'Validates schema only', 'In Spring Data JPA, what does ''ddl-auto: update'' do?', 2),
(15, 'B', 'MEDIUM', 'OncePerRequestFilter guarantees a single execution per request, commonly used for JWT authentication filters.', 'DispatcherServlet', 'OncePerRequestFilter', 'ViewResolver', 'HandlerMapping', 'Which Spring Security component authenticates incoming requests once per request in a filter chain?', 2);    
INSERT INTO "PUBLIC"."QUESTIONS" VALUES
(16, 'B', 'MEDIUM', '201 Created is conventionally returned after a successful resource-creating POST.', 'GET requests fetching a resource', 'POST requests that successfully create a resource', 'DELETE requests', 'PUT requests updating a resource', 'What HTTP status does @ResponseStatus(HttpStatus.CREATED) typically pair with?', 2),
(17, 'B', 'MEDIUM', '@Transactional demarcates a transactional boundary and rolls back on unchecked exceptions by default.', 'Runs the method in a separate thread', 'Wraps the method in a database transaction, rolling back on runtime exceptions', 'Caches the method result', 'Logs method execution time', 'What does @Transactional do when applied to a service method?', 2),
(18, 'A', 'MEDIUM', 'spring-boot-starter-actuator adds production-ready monitoring endpoints like /actuator/health.', 'spring-boot-starter-actuator', 'spring-boot-starter-web', 'spring-boot-starter-test', 'spring-boot-starter-security', 'Which starter would you add to expose actuator health/metrics endpoints?', 2),
(19, 'B', 'MEDIUM', 'Constructor injection allows final fields and makes required dependencies explicit and easily mockable in tests.', 'Faster runtime performance', 'Enables immutable dependencies and easier testing', 'Requires less code', 'Works only with @Autowired', 'What is the primary benefit of constructor injection over field injection?', 2),
(20, 'B', 'MEDIUM', '@PreAuthorize with a SpEL role expression enforces method-level role-based access control.', '@RequestMapping', '@PreAuthorize("hasRole(''ADMIN'')")', '@Valid', '@ResponseBody', 'Which annotation restricts an endpoint to users with a specific role?', 2),
(21, 'B', 'MEDIUM', 'Amazon S3 is AWS''s scalable object storage service.', 'EBS', 'S3', 'EFS', 'RDS', 'Which AWS service provides object storage?', 3),
(22, 'C', 'MEDIUM', 'AWS secures the cloud infrastructure; customers secure what they configure and store in the cloud.', 'AWS handles all security', 'Customer handles all security', 'Security responsibilities split between AWS and the customer', 'There is no shared responsibility in AWS', 'What is the AWS shared responsibility model primarily about?', 3),
(23, 'B', 'MEDIUM', 'AWS Lambda runs code in response to events without provisioning or managing servers.', 'EC2', 'Lambda', 'Lightsail', 'Elastic Beanstalk', 'Which service is used for serverless compute in AWS?', 3),
(24, 'B', 'MEDIUM', 'Amazon RDS manages relational databases like MySQL, PostgreSQL, and Aurora.', 'DynamoDB', 'RDS', 'S3', 'SQS', 'Which AWS service provides a managed relational database?', 3),
(25, 'B', 'MEDIUM', 'IAM policies are JSON documents that define allowed or denied actions on AWS resources.', 'Network routing rules', 'Permissions for actions on AWS resources', 'Billing thresholds', 'EC2 instance types', 'What does an IAM policy define?', 3),
(26, 'B', 'MEDIUM', 'Amazon SQS provides fully managed message queuing for decoupling microservices.', 'SNS', 'SQS', 'CloudFront', 'Route 53', 'Which AWS service is best suited for decoupling application components via message queues?', 3),
(27, 'B', 'MEDIUM', 'Availability Zones are physically separate data centers within a Region, used for high availability.', 'A billing region', 'An isolated data center location within an AWS Region for fault tolerance', 'A type of IAM role', 'A CDN edge location', 'What is the purpose of an Availability Zone?', 3),
(28, 'C', 'MEDIUM', 'Reserved Instances and Savings Plans offer significant discounts in exchange for a usage commitment.', 'On-Demand', 'Spot Instances', 'Reserved Instances / Savings Plans', 'Free Tier', 'Which pricing model offers the largest discount for steady-state, predictable workloads?', 3),
(29, 'A', 'MEDIUM', 'Amazon CloudFront is AWS''s content delivery network (CDN).', 'CloudFront', 'VPC', 'IAM', 'CloudTrail', 'Which AWS service delivers content to users with low latency via edge locations?', 3),
(30, 'B', 'MEDIUM', 'AWS CloudTrail logs API activity across an account for governance and auditing.', 'CloudWatch', 'CloudTrail', 'Config', 'Inspector', 'Which service records API calls made within an AWS account for auditing?', 3);               
INSERT INTO "PUBLIC"."QUESTIONS" VALUES
(31, 'B', 'MEDIUM', 'ARM is the deployment and management layer for creating, updating, and organizing Azure resources.', 'Billing invoices only', 'Deploying, managing, and organizing Azure resources as a group', 'Monitoring network traffic', 'User authentication only', 'What is Azure Resource Manager (ARM) primarily used for?', 4),
(32, 'A', 'MEDIUM', 'Azure Blob Storage is Microsoft''s object storage solution for unstructured data.', 'Azure Blob Storage', 'Azure SQL Database', 'Azure Functions', 'Azure DevOps', 'Which Azure service provides scalable object storage?', 4),
(33, 'B', 'MEDIUM', 'Azure AD (Microsoft Entra ID) is Azure''s cloud-based identity and access management service.', 'Object storage', 'Identity and access management', 'Virtual networking', 'Container orchestration', 'What is the purpose of Azure Active Directory (Microsoft Entra ID)?', 4),
(34, 'B', 'MEDIUM', 'Azure Functions runs event-triggered code without requiring the user to manage servers.', 'Azure Virtual Machines', 'Azure Functions', 'Azure Kubernetes Service', 'Azure Batch', 'Which Azure compute service is fully serverless (event-driven, no server management)?', 4),
(35, 'B', 'MEDIUM', 'Resource Groups group related resources for unified lifecycle management, access control, and billing.', 'A billing currency', 'A logical container for resources sharing the same lifecycle', 'A network security rule', 'A VM image', 'What does an Azure Resource Group represent?', 4),
(36, 'B', 'MEDIUM', 'The Azure Pricing Calculator estimates the cost of Azure services based on configuration.', 'Azure Monitor', 'Azure Pricing Calculator', 'Azure Advisor', 'Azure Policy', 'Which Azure pricing tool estimates the cost of Azure products before deployment?', 4),
(37, 'B', 'MEDIUM', 'Azure Virtual Machines is Azure''s core IaaS offering for provisioning VMs.', 'Azure App Service', 'Azure Virtual Machines', 'Azure Logic Apps', 'Azure Cognitive Services', 'Which service provides Infrastructure as a Service (IaaS) virtual machines in Azure?', 4),
(38, 'B', 'MEDIUM', 'Availability Zones are physically separate locations within an Azure region that protect against datacenter failures.', 'Lower storage cost only', 'Protection against datacenter-level failures within a region', 'Faster DNS resolution', 'Simplified billing', 'What is the main benefit of Azure Availability Zones?', 4),
(39, 'A', 'MEDIUM', 'Azure Policy evaluates resources for compliance with defined rules and can enforce or audit them.', 'Azure Policy', 'Azure Monitor', 'Azure Backup', 'Azure Bastion', 'Which Azure governance feature enforces organizational rules on resource properties?', 4),
(40, 'B', 'MEDIUM', 'An SLA defines Microsoft''s guaranteed performance and uptime commitments for a given Azure service.', 'Defining CPU architecture', 'Microsoft''s guaranteed uptime/performance commitment for a service', 'Setting resource group names', 'Configuring VNets', 'What is the Azure Service Level Agreement (SLA) used for?', 4);         
CREATE MEMORY TABLE "PUBLIC"."SUBSCRIPTION_PLAN"(
    "PLAN_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 5) DEFAULT ON NULL NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "DURATION_IN_MONTHS" INTEGER NOT NULL,
    "PLAN_NAME" CHARACTER VARYING(100) NOT NULL,
    "PRICE" NUMERIC(10, 2) NOT NULL,
    "QUESTION_LIMIT" INTEGER NOT NULL,
    "STATUS" ENUM('ACTIVE', 'INACTIVE') NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL
);             
ALTER TABLE "PUBLIC"."SUBSCRIPTION_PLAN" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("PLAN_ID");       
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.SUBSCRIPTION_PLAN;       
INSERT INTO "PUBLIC"."SUBSCRIPTION_PLAN" VALUES
(1, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:22.879874+00', 12, 'Free', 0.00, 50, 'ACTIVE', TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:22.879874+00'),
(2, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:22.879874+00', 12, 'Basic', 99.00, 500, 'ACTIVE', TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:22.879874+00'),
(3, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:22.879874+00', 12, 'Premium', 299.00, 2000, 'ACTIVE', TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:22.879874+00'),
(4, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:22.879874+00', 12, 'Enterprise', 999.00, 10000, 'ACTIVE', TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:22.879874+00');  
CREATE MEMORY TABLE "PUBLIC"."TEST_ANSWERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "CORRECT" BOOLEAN NOT NULL,
    "SELECTED_OPTION" CHARACTER VARYING(10),
    "QUESTION_ID" BIGINT NOT NULL,
    "TEST_ATTEMPT_ID" BIGINT NOT NULL
);          
ALTER TABLE "PUBLIC"."TEST_ANSWERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TEST_ANSWERS;            
CREATE MEMORY TABLE "PUBLIC"."TESTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) DEFAULT ON NULL NOT NULL,
    "COMPLETED_AT" TIMESTAMP(6) WITH TIME ZONE,
    "DURATION_SECONDS" INTEGER,
    "SCORE" INTEGER,
    "STARTED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "STATUS" CHARACTER VARYING(20) NOT NULL,
    "TOTAL_QUESTIONS" INTEGER NOT NULL,
    "EXAM_ID" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL
);     
ALTER TABLE "PUBLIC"."TESTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4C" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TESTS;   
CREATE MEMORY TABLE "PUBLIC"."USER_SUBSCRIPTION"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) DEFAULT ON NULL NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "END_DATE" DATE NOT NULL,
    "REMAINING_QUESTION_COUNT" INTEGER NOT NULL,
    "START_DATE" DATE NOT NULL,
    "SUBSCRIPTION_STATUS" ENUM('ACTIVE', 'CANCELLED', 'EXPIRED') NOT NULL,
    "UPDATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "VERSION" BIGINT NOT NULL,
    "PLAN_ID" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL
);   
ALTER TABLE "PUBLIC"."USER_SUBSCRIPTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");            
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USER_SUBSCRIPTION;       
INSERT INTO "PUBLIC"."USER_SUBSCRIPTION" VALUES
(1, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.303672+00', DATE '2027-08-06', 10000, DATE '2026-08-06', 'ACTIVE', TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.303672+00', 0, 4, 1),
(2, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.315802+00', DATE '2027-08-06', 50, DATE '2026-08-06', 'ACTIVE', TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.315802+00', 0, 1, 2);              
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) DEFAULT ON NULL NOT NULL,
    "ACCOUNT_LOCKED_UNTIL" TIMESTAMP(6) WITH TIME ZONE,
    "ACTIVE" BOOLEAN NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "FAILED_LOGIN_ATTEMPTS" INTEGER NOT NULL,
    "MOBILE_NUMBER" CHARACTER VARYING(20),
    "NAME" CHARACTER VARYING(100) NOT NULL,
    "PASSWORD" CHARACTER VARYING(255) NOT NULL,
    "PASSWORD_CHANGED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "PASSWORD_RESET_REQUIRED" BOOLEAN NOT NULL,
    "ROLE" ENUM('ADMIN', 'USER') NOT NULL,
    "TEMPORARY_PASSWORD_EXPIRY" TIMESTAMP(6) WITH TIME ZONE,
    "TEMPORARY_PASSWORD" CHARACTER VARYING(255)
);       
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("ID");       
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
INSERT INTO "PUBLIC"."USERS" VALUES
(1, NULL, TRUE, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.146706+00', 'admin@interviewpilot.dev', 0, NULL, 'Admin', '$2a$10$mzzn5z715F.GnjLJtgtue.hUQb8uaxHY8IEXRrZ7To2qJ1c9Vso5C', TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.146706+00', FALSE, 'ADMIN', NULL, NULL),
(2, NULL, TRUE, TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.274645+00', 'demo@interviewpilot.dev', 0, NULL, 'Demo Candidate', '$2a$10$Nb8DuyLL0KCaz1sOwfeXWOcwmhs5urA0pxjm9t3RLEPkWUWv3Bf/y', TIMESTAMP WITH TIME ZONE '2026-08-06 09:17:23.274645+00', FALSE, 'USER', NULL, NULL);    
ALTER TABLE "PUBLIC"."PAYMENT_ORDER" ADD CONSTRAINT "PUBLIC"."UK_PAYMENT_ORDER_RAZORPAY_ORDER_ID" UNIQUE NULLS DISTINCT ("RAZORPAY_ORDER_ID");
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UK6DOTKOTT2KJSP8VW4D0M25FB7" UNIQUE NULLS DISTINCT ("EMAIL");           
ALTER TABLE "PUBLIC"."PLAN_QUESTION" ADD CONSTRAINT "PUBLIC"."UK_PLAN_QUESTION_PLAN_ID_QUESTION_ID" UNIQUE NULLS DISTINCT ("PLAN_ID", "QUESTION_ID");         
ALTER TABLE "PUBLIC"."PAYMENT_TRANSACTION" ADD CONSTRAINT "PUBLIC"."UK_PAYMENT_TRANSACTION_RAZORPAY_PAYMENT_ID" UNIQUE NULLS DISTINCT ("RAZORPAY_PAYMENT_ID");
ALTER TABLE "PUBLIC"."USER_SUBSCRIPTION" ADD CONSTRAINT "PUBLIC"."FKN4XRJHA3C12VP530Y3J0OGEF2" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;              
ALTER TABLE "PUBLIC"."TEST_ANSWERS" ADD CONSTRAINT "PUBLIC"."FKFXNPJLREOS87C1DQCQMT820LU" FOREIGN KEY("QUESTION_ID") REFERENCES "PUBLIC"."QUESTIONS"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."PAYMENT_ORDER" ADD CONSTRAINT "PUBLIC"."FKKH180WY67T68TJBVGX916WO8C" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."PAYMENT_TRANSACTION" ADD CONSTRAINT "PUBLIC"."FKMDEVRIFDIBHJ2OC6KM8FJURWK" FOREIGN KEY("ORDER_ID") REFERENCES "PUBLIC"."PAYMENT_ORDER"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."PAYMENT_ORDER" ADD CONSTRAINT "PUBLIC"."FKO63JNUF3Y5I5676PNN41O2RJP" FOREIGN KEY("PLAN_ID") REFERENCES "PUBLIC"."SUBSCRIPTION_PLAN"("PLAN_ID") NOCHECK; 
ALTER TABLE "PUBLIC"."PAYMENT_TRANSACTION" ADD CONSTRAINT "PUBLIC"."FKDE3RTHYU0PI1QIABAT0T2RCA" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."TESTS" ADD CONSTRAINT "PUBLIC"."FKJ48XN6UMWT6LDY4V97IV2T1K3" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."TESTS" ADD CONSTRAINT "PUBLIC"."FKF6MU8NXXVTBPBL6QI188R6CSM" FOREIGN KEY("EXAM_ID") REFERENCES "PUBLIC"."EXAMS"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."USER_SUBSCRIPTION" ADD CONSTRAINT "PUBLIC"."FK5JWAYHO30SJ0JBG6LLCSQE88H" FOREIGN KEY("PLAN_ID") REFERENCES "PUBLIC"."SUBSCRIPTION_PLAN"("PLAN_ID") NOCHECK;             
ALTER TABLE "PUBLIC"."QUESTIONS" ADD CONSTRAINT "PUBLIC"."FKRK78BMT53FNS7NP8CASQA3Q44" FOREIGN KEY("EXAM_ID") REFERENCES "PUBLIC"."EXAMS"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."TEST_ANSWERS" ADD CONSTRAINT "PUBLIC"."FKJ9I0WKGE6Q2DOVXGIBE2NRTH3" FOREIGN KEY("TEST_ATTEMPT_ID") REFERENCES "PUBLIC"."TESTS"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."PLAN_QUESTION" ADD CONSTRAINT "PUBLIC"."FK4O2L3X5O1M8L84X17B7OUDGUW" FOREIGN KEY("QUESTION_ID") REFERENCES "PUBLIC"."QUESTIONS"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."PLAN_QUESTION" ADD CONSTRAINT "PUBLIC"."FKOYMH23DD67JGBWVYOYQ8DUPH9" FOREIGN KEY("PLAN_ID") REFERENCES "PUBLIC"."SUBSCRIPTION_PLAN"("PLAN_ID") NOCHECK; 
